name: Docker
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: qemu setup
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm/v7'
    - name: buildx setup
      uses: docker/setup-buildx-action@v2
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: build image
      uses: docker/build-push-action@v3
      with:
        platforms: 'linux/arm/v7'
        push: true
        tags: dtext/bme280ws:latest