name: Docker
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: qemu setup
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64'
    - name: buildx setup
      uses: docker/setup-buildx-action@v2
    - name: check platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: build image
      uses: docker/build-push-action@v3
      with:
        platforms: 'linux/arm64'
        push: true
        tags: dtext/bme280ws:latest